baseURL = 'https://theautonomouscreator.netlify.app/'
languageCode = 'en-us'
title = 'The Autonomous Creator'
theme = 'ananke'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false

[params]
custom_css = ["custom.css"]
favicon = "/Logo_wo_bg.png" 

# Social media icons
[[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/szym0n_24/"

[[params.social]]
  name = "facebook"
  url = "https://www.facebook.com/szymon.derlecki.3/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    title = "The Autonomous Creator"
    weight = 1

    [[languages.en.menu.main]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About me"
      url = "/en/categories/bio/"
      weight = 6

    [[languages.en.menu.main]]
      identifier = "studies"
      name = "Studies in Denmark"
      url = "/en/categories/studies-in-denmark/"
      weight = 2

    [[languages.en.menu.main]]
      identifier = "tech"
      name = "Technologies & Projects"
      url = "/en/categories/technologies-and-projects/"
      weight = 3

    [[languages.en.menu.main]]
      identifier = "on-the-go"
      name = "On The Go"
      url = "/en/categories/on-the-go/"
      weight = 4

    [[languages.en.menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/en/contact/"
      weight = 5

  [languages.pl]
    languageCode = "pl"
    languageName = "Polski"
    title = "The Autonomous Creator"
    weight = 2

    [[languages.pl.menu.main]]
      identifier = "home"
      name = "Strona Główna"
      url = "/pl/"
      weight = 1

    [[languages.pl.menu.main]]
      identifier = "about"
      name = "O mnie"
      url = "/pl/categories/bio/"
      weight = 6

    [[languages.pl.menu.main]]
      identifier = "studies"
      name = "Studia w Danii"
      url = "/pl/categories/studia-w-danii/"
      weight = 2

    [[languages.pl.menu.main]]
      identifier = "tech"
      name = "Technologie i Projekty"
      url = "/pl/categories/technologie-i-projekty/"
      weight = 3

    [[languages.pl.menu.main]]
      identifier = "on-the-go"
      name = "On The Go"
      url = "/pl/categories/on-the-go/"
      weight = 4

    [[languages.pl.menu.main]]
      identifier = "contact"
      name = "Kontakt"
      url = "/pl/kontakt/"
      weight = 5