baseURL = 'https://theautonomousstudent.netlify.app/'
languageCode = 'en-us'
title = 'The Autonomous Student'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

   [[menu.main]]
    name = "About Me"
    url = "/categories/aboutme"
    weight = 5

  [[menu.main]]
   name = "Studying in Denmark"
   url = "/categories/studyingindenmark"
   weight = 2

  [[menu.main]]
   name = "Advanced Technologies"
   url = "/categories/advancedtechnologies"
   weight = 3

  [[menu.main]]
   name = "On The Go"
   url = "/categories/onthego"
   weight = 4